FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS final
WORKDIR /app

ENV ASPNETCORE_URLS=http://0.0.0.0:8080
ENV ASPNETCORE_ENVIRONMENT=Production

COPY . .
RUN test -f /app/MainApi.dll

EXPOSE 8080

ENTRYPOINT ["dotnet", "MainApi.dll"]
